chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.chat_home, name='chat_home'),
    path('chat/', views.create_message, name='chat')

]

gallery/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.gallery, name='gallery'),
    path("post/<slug:slug>/", views.detail, name="detail"),
    path('add', views.add, name='add'),
    path("post/<slug:slug>/add_comment/", views.add_comment, name="add_comment"),
]

registration/urls.py
from django.urls import path
from .views import register
from django.contrib.auth import views as auth_views
from . import views

app_name = "account"


urlpatterns = [
    path('register/', register, name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

wiki/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('chat/', include('chat.urls')),
    path('character/', include('character.urls')),
    path('gallery/', include('gallery.urls')),
    path('account/', include('registration.urls', namespace="account")),
    path('news/', include('news.urls')),
    ] +static(settings.STATIC_URL , document_root=settings.STATIC_ROOT) +static(settings.MEDIA_URL ,document_root=settings.MEDIA_ROOT)

gallery/models.py
from django.db import models
from django.contrib.auth.models import User


class Photo(models.Model):
    name = models.CharField("Photo name", max_length=250, null=True)
    slug = models.SlugField("Slug fiels", max_length=250, null=True)
    image = models.ImageField(upload_to='post_images/', null=True)
    created = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'photo'
        verbose_name_plural = 'photos'

        indexes = [
            models.Index(fields=['-created']),
            ]


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Photo, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]
        indexes = [models.Index(fields=["created_at"])]

    def __str__(self):
        return f"{self.user.username} - {self.post.name} - {self.created_at}"

gallery/forms.py
from .models import Comment, Photo
from django.forms import ModelForm, FileInput, Textarea

class PhotoForm(ModelForm):
    class Meta:
        model = Photo
        fields = ["name", "slug", "image"]

        widgets = {
            'image': FileInput(attrs={
                'class': 'form-control',
            })
        }



class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': Textarea(attrs={'cols': 80, 'rows': 3}),
        }

gallery/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from .models import Photo
from .forms import PhotoForm, CommentForm
from django.contrib.auth.decorators import login_required

def gallery(request):
    gallery = Photo.objects.all()
    return render(request, 'gallery/gallery.html', {'gallery': gallery})

def detail(request, slug):
    # Используйте slug для поиска фото в базе данных
    photo = get_object_or_404(Photo, slug=slug)
    return render(request, "gallery/photo_detail.html", {"photo": photo})


@login_required
def add(request):
    error = ''
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('gallery')
        else:
            data = {
                'form': form,
                'error': 'Invalid form data. Please correct the errors below.',
            }
            return render(request, 'gallery/add.html', data)
    else:
        form = PhotoForm()

    data = {
        'form': form,
        'error': error,
    }

    return render(request, 'gallery/add.html', data)

@login_required
def add_comment(request, slug):
    post = get_object_or_404(Photo, slug=slug)
    comment = None
    if request.method == "POST":
        form = CommentForm(data=request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            return redirect(reverse("detail", args=[post.slug]))
    else:
        form = CommentForm()
    return render(
        request,
        "add_comment.html",
        {
            "form": form,
            "post": post,
            "comment": comment,
        },
    )

templates/gallery/add.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>photo</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css'%}">
    <link rel="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4.2/css/fontawesome.min.css">
</head>
<body>
    <aside>
        <img src="{% static 'main/img/Без названия.jpeg'%}" alt="logo">
        <span class="logo">Vinland Saga</span>
        <h3>Navigation</h3>
        <ul>
            <a href="{% url 'home' %}"><li> <i class="fa-solid fa-house"></i>Main</li>
            <a href="{% url 'gallery' %}"><li> <i class="fa-solid fa-earth-americas"></i> Gallery</li>
            <a href="{% url 'character' %}"><li> <i class="fa-solid fa-earth-americas"></i> Character</li>
                <a href="{% url 'news_home' %}"><li> <i class="fa-solid fa-earth-americas"></i>  • news</li></a>

        </ul>
    </aside>
    <main>
        <div class="features">
            <h1>Add photo</h1>
          <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                     <button class="btn btn-success" type="submit">Add photo</button>
          </form>
        </div>

    </main>

</body>
</html>

templates/gallery/gallery.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>gallery</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css'%}">
    <link rel="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4.2/css/fontawesome.min.css">
</head>
<body>
<style>

    img.other {
        width: 80px;
        height: 80px;
        border-radius: 80px;
        border: 2px solid white;
        transform: translateX(-250px)
    }

    img {
        width: 320px;
        height: 320px;
        margin-left: 250px;
    }



    aside hr {
    border: 2px solid #F5F5DC;
    margin-top: 10px;
    margin-bottom: 10px;
    }

    body {
       background-color: #F5F5DC;
    }
    h1.gallery {
        transform: translateY(-50px)
    }

     hr.line {
                width: 50%;
                border-width: 2px;
                border-color: white;
                margin-left: 25%;
                transform: translate(250px,-20px)
            }

</style>
    <aside>
        <img class="other" src="https://sun9-77.userapi.com/impg/PEh5iOf1H8k0e9Co06aQmlRzaNp88EAwPhYZvA/SPiuOm8Z6SY.jpg?size=1280x918&quality=96&sign=15cc9e82ef6e529b8b2cc32c8c42837e&c_uniq_tag=A23SjHkSK_4JhxK1llBnJsyhsZrQ6luShW31nhtGXeU&type=album" alt="logo">
        <span class="logo">Vinland Saga</span>
        <hr>
        <h3>Navigation</h3>
        <ul>
            <a href="{% url 'home' %}"><li> <i class="fa-solid fa-house"></i>  • Main</li>
            <a href="{% url 'gallery' %}"><li> <i class="fa-solid fa-earth-americas"></i> • Gallery</li>
            <a href="{% url 'character' %}"><li> <i class="fa-solid fa-earth-americas"></i>  • Characters</li><a></a>
                <a href="{% url 'news_home' %}"><li> <i class="fa-solid fa-earth-americas"></i>  • News</li></a>

        </ul>
    </aside>
    <main>
        <div class="features">
            <h1 class="gallery">Gallery</h1>
            <hr class="line">
            {% if request.user.is_authenticated %}
                <a href="{% url 'add' %}"><li><button class="btn btn-info"><i class="fas fa-plus-circle"></i> Add photo</button></li></a>
            {% else %}
                <a href="{% url 'account:login' %}"><li><button class="btn btn-info"><i class="fas fa-plus-circle"></i> Login to add</button></li></a>
            {% endif %}
        </div>
        {% if gallery %}
            {%  for el in gallery %}
            <a href="{% url 'detail' slug=el.slug %}"><img src="{{el.image.url}}"></a>
            {% endfor %}
        {% else %}}
        <h3>There's nothing</h3>
        {% endif %}
    </main>

</body>
</html>

templates/gallery/photo_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>gallery</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css'%}">
    <link rel="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4.2/css/fontawesome.min.css">
</head>
<body>
<style>

    img.other {
        width: 80px;
        height: 80px;
        border-radius: 80px;
        border: 2px solid white;
        transform: translateX(-250px)
    }

    img {
        width: 320px;
        height: 320px;
        margin-left: 250px;
    }



    aside hr {
    border: 2px solid #F5F5DC;
    margin-top: 10px;
    margin-bottom: 10px;
    }

    body {
       background-color: #F5F5DC;
    }
    h1.gallery {
        transform: translateY(-50px)
    }

     hr.line {
                width: 50%;
                border-width: 2px;
                border-color: white;
                margin-left: 25%;
                transform: translate(250px,-20px)
            }

</style>
    <aside>
        <img class="other" src="https://sun9-77.userapi.com/impg/PEh5iOf1H8k0e9Co06aQmlRzaNp88EAwPhYZvA/SPiuOm8Z6SY.jpg?size=1280x918&quality=96&sign=15cc9e82ef6e529b8b2cc32c8c42837e&c_uniq_tag=A23SjHkSK_4JhxK1llBnJsyhsZrQ6luShW31nhtGXeU&type=album" alt="logo">
        <span class="logo">Vinland Saga</span>
        <hr>
        <h3>Navigation</h3>
        <ul>
            <a href="{% url 'home' %}"><li> <i class="fa-solid fa-house"></i>  • Main</li>
            <a href="{% url 'gallery' %}"><li> <i class="fa-solid fa-earth-americas"></i> • Gallery</li>
            <a href="{% url 'character' %}"><li> <i class="fa-solid fa-earth-americas"></i>  • Characters</li><a></a>
                <a href="{% url 'news_home' %}"><li> <i class="fa-solid fa-earth-americas"></i>  • News</li></a>

        </ul>
    </aside>
    <main>
        <div class="features">
            <h1 class="gallery">Post</h1>
            <hr class="line">
            <h3>{{photo.name}}</h3>
            <img src="{{photo.image.url}}">
              <div style="margin-top: 20px;">
    <h4>Comments</h4>
    {% if request.user.is_authenticated %}
      <form method="post" action="{% url 'add_comment' slug=photo.slug %}">
        {% csrf_token %}
        {{ form.text }}
        <button type="submit" class="btn btn-primary">Add Comment</button>
      </form>
    {% else %}
      <p><a href="{% url 'account:login' %}">Log in</a> to add comments.</p>
    {% endif %}

    {% for comment in photo.comment_set.all %}
      <div style="border: 1px solid #ddd; padding: 10px; margin-top: 10px;">
        <p style="color: #777; font-size: 12px;">- {{ comment.user.username }}</p>
        <p>{{ comment.text }}</p>
      </div>
    {% endfor %}
  </div>
    </main>

</body>
</html>