chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.chat_home, name='chat_home'),
    path('chat/', views.create_message, name='chat')

]

registration/urls.py
from django.urls import path
from .views import register
from django.contrib.auth import views as auth_views
from . import views

app_name = "account"


urlpatterns = [
    path('register/', register, name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

wiki/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('chat/', include('chat.urls')),
    path('character/', include('character.urls')),
    path('gallery/', include('gallery.urls')),
    path('account/', include('registration.urls', namespace="account")),
    path('news/', include('news.urls')),
    ] +static(settings.STATIC_URL , document_root=settings.STATIC_ROOT) +static(settings.MEDIA_URL ,document_root=settings.MEDIA_ROOT)

templates/add_comment.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>gallery</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css'%}">
    <link rel="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4.2/css/fontawesome.min.css">
</head>
<body>
<style>

    img.other {
        width: 80px;
        height: 80px;
        border-radius: 80px;
        border: 2px solid white;
        transform: translateX(-250px)
    }

    img {
        width: 320px;
        height: 320px;
        margin-left: 250px;
    }



    aside hr {
    border: 2px solid #F5F5DC;
    margin-top: 10px;
    margin-bottom: 10px;
    }

    body {
       background-color: #F5F5DC;
    }
    h1.gallery {
        transform: translateY(-50px)
    }

     hr.line {
                width: 50%;
                border-width: 2px;
                border-color: white;
                margin-left: 25%;
                transform: translate(250px,-20px)
            }

</style>
    <aside>
        <img class="other" src="https://sun9-77.userapi.com/impg/PEh5iOf1H8k0e9Co06aQmlRzaNp88EAwPhYZvA/SPiuOm8Z6SY.jpg?size=1280x918&quality=96&sign=15cc9e82ef6e529b8b2cc32c8c42837e&c_uniq_tag=A23SjHkSK_4JhxK1llBnJsyhsZrQ6luShW31nhtGXeU&type=album" alt="logo">
        <span class="logo">Vinland Saga</span>
        <hr>
        <h3>Navigation</h3>
        <ul>
            <a href="{% url 'home' %}"><li> <i class="fa-solid fa-house"></i>  • Main</li>
            <a href="{% url 'gallery' %}"><li> <i class="fa-solid fa-earth-americas"></i> • Gallery</li>
            <a href="{% url 'character' %}"><li> <i class="fa-solid fa-earth-americas"></i>  • Characters</li><a></a>
                <a href="{% url 'news_home' %}"><li> <i class="fa-solid fa-earth-americas"></i>  • News</li></a>

        </ul>
    </aside>
    <main>
          <div style="width: 50%; margin: auto; padding: 20px; border: 1px solid #ccc; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
    <h2 style="text-align: center;">Add comment</h2>
    <h3 style="text-align: center;">{{ photo.name }}</h3>

    <form method="post" action="{% url 'add_comment' slug=post.slug %}?next={{ request.path }}" style="text-align: center;">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" style="margin-top: 10px; padding: 10px 15px; background-color: #007bff; color: #fff; border: none; border-radius: 4px; cursor: pointer; transition: background-color 0.3s ease;">Добавить комментарий</button>
   </form>

    </main>

</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css'%}">
    <link rel="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4.2/css/fontawesome.min.css">
</head>
<body>
<style>
    img {
       width: 80px;
       height: 80px;
       border-radius: 80px;
       border: 2px solid white;
       }


    span.logo {

        transform: translateX(15px);
        color: #F5F5DC
       }

    aside hr {
    border: 2px solid #F5F5DC;
    margin-top: 10px;
    margin-bottom: 10px;
    }

    img.min {
    border-radius: 1px solid;
    background-color: black;
    font-size: 5px;
    }

    hr.line {
        width: 50%;
        border-width: 2px;
        border-color: white;
        margin-left: 25%;
    }


</style>
    <aside>
        <img src="https://sun9-77.userapi.com/impg/PEh5iOf1H8k0e9Co06aQmlRzaNp88EAwPhYZvA/SPiuOm8Z6SY.jpg?size=1280x918&quality=96&sign=15cc9e82ef6e529b8b2cc32c8c42837e&c_uniq_tag=A23SjHkSK_4JhxK1llBnJsyhsZrQ6luShW31nhtGXeU&type=album" alt="logo">
        <span class="logo">Vinland Saga</span>
        <hr>
        <h3>Navigation</h3>
        <ul>
            <a href="{% url 'home' %}"><li> <i class="fa-solid fa-house"></i> • Main</li>
            <a href="{% url 'gallery' %}"><li> <i class="fa-solid fa-earth-americas"></i>  • Gallery</li>
            <a href="{% url 'character' %}"><li> <i class="fa-solid fa-earth-americas"></i> • Characters</li>
                <a href="{% url 'news_home' %}"><li> <i class="fa-solid fa-earth-americas"></i>  • News</li></a>
        </ul>
    </aside>

    <main>


        <div class="features">
            <h1>Welcome to Vinland!</h1>
            <hr class="line">
            <p> Greetings, traveler, to the wiki dedicated to one of the greatest sagas – Vinland Saga. Here, you'll discover endless Viking fields, snow-covered Scandinavian forests, and gripping battles that will leave a mark on history.

Vinland Saga is not just a story; it's an epic full of thrilling adventures and the destinies of characters. On this wiki, you can delve into the heroes, historical facts, and Viking culture that compose the essence of this captivating world.

Let's open the doors to the past together, where the secrets of great warriors are hidden, and where every page of their fate is filled with courage and determination. Join the community of Vinland Saga fans – a place where passion for history meets the magic of Viking adventures.

Welcome to Vinland, where every fan becomes part of the legend!</p>
             <a href="{% url 'account:register' %}" class="btn btn-success">Registration</a>
            {% if request.user.is_authenticated %}
            <form action="{% url 'account:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-success">Logout</button>
            </form>
            {% else %}
            <a href="{% url 'account:login' %}" class="btn btn-success">login</a>
            {% endif %}
        </div>
    </main>

</body>
</html>